### ISSUE TITLE
Bug: Running server crashes with error 'Error: Cannot find module './connectors/viewpoint2''

### ISSUE THREAD

**Issue by shstkvch** [LibrariesHacked/catalogues-api#5]
```
david@Davids-iMac catalogues-api % node server.js
library thing connector loading...
open library connector loading...
spydus connector loading...
enterprise connector loading...
vubis connector loading
prism3 connector loading...
iguana connector loading...
ibistro connector loading...
koha connector loading...
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module './connectors/viewpoint2'
```

It seems the issue is the [library data JSON](https://github.com/LibrariesHacked/catalogues-api/blob/master/data/data.json) file is out of date and references a connector that no longer exists. There is a connector called viewpoint3 however

**Comment by DaveBathnes** [comment]
Closing this now - code has been merged that removes viewpoint2 as a connector as there are no remaining library services using it.
